### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'roleList')

### ISSUE THREAD

**Issue by Yoimiyacat** [erzaozi/waves-plugin#1]
[21:15:45.069][INFO][xxxxx <= xxxx, xxxx] 群消息：[派魔喵の猫爬架<$ǿĀC><$ǿĀC
           >, 群员] #鸣潮信息
[21:15:45.270][INFO][群号, 群员][#鸣潮信息][鸣潮-用户信息(userInfo)][开始处理]
[21:15:45.450][INFO][TRSSYz] 获取可用性成功：账号可用
[21:15:45.502][INFO][TRSSYz] 获取我的资料成功
[21:15:45.559][INFO][TRSSYz] 获取共鸣者成功
[21:15:45.560][ERRO][鸣潮-用户信息(userInfo)][群号, 群员][#鸣潮信息] TypeError: Cannot read properties of null (reading 'roleList')
    at Render.userInfo (file:///home/ubuntu/Yunzai/plugins/waves-plugin/model/render.js:9:18)
    at UserInfo.userInfo (file:///home/ubuntu/Yunzai/plugins/waves-plugin/apps/User.js:51:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///home/ubuntu/Yunzai/lib/plugins/loader.js:253:41) {
  [stack]: "TypeError: Cannot read properties of null (reading 'roleList')\n" +
    '    at Render.userInfo (file:///home/ubuntu/Yunzai/plugins/waves-plugin/model/render.js:9:18)\n' +
    '    at UserInfo.userInfo (file:///home/ubuntu/Yunzai/plugins/waves-plugin/apps/User.js:51:48)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PluginsLoader.deal (file:///home/ubuntu/Yunzai/lib/plugins/loader.js:253:41)',
  [message]: "Cannot read properties of null (reading 'roleList')"

**Comment by CikeyQi** [comment]
在库街区APP中的 `数据终端` 内打开所有项目的 `对外展示` 开关
