### ISSUE TITLE
请求适配ws-plugin

### ISSUE THREAD

**Issue by BeggingHorse** [erzaozi/waves-plugin#15]
用的red协议，~登录帮助、~抽卡帮助等都发不出去，~签到、~卡片等正常

[12:44:03.234][ERRO] 发送消息错误:{}
[12:44:03.235][ERRO] [ws-plugin] 发送消息错误: message is empty
[12:44:03.239][MARK] [鸣潮-抽卡统计][gachaCount] ～抽卡统计https://aki-gm-resources.aki-game.com/aki/gacha/index.html#/record?svr_id=76402ebe2c39f0... 处理完成 17524ms
[12:44:03.241][ERRO] ApiRejection {
  code: -60,
  message: 'client not online (cmd: ImgStore.GroupPicUp)'
}
[12:44:12.106][ERRO] [openai][dyr]
[12:44:12.107][ERRO] TypeError: Cannot read properties of undefined (reading 'includes')
    at example.dyr (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/earth-k-plugin/apps/openai.js:83:19)
    at PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/lib/plugins/loader.js:269:60)

**Comment by CikeyQi** [comment]
应该请求 ws-plugin 适配 `Bot.makeForwardMsg` 方法制作合并转发消息，本插件不会再考虑使用其他方法制作转发消息
