### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'phantomList')

### ISSUE THREAD

**Issue by Yoimiyacat** [erzaozi/waves-plugin#2]
[21:15:22.015][INFO][xxxxx <= xxxxx, xxxxx] 群消息：[派魔喵の猫爬架<$ǿĀC><$ǿĀC
           >, 要高考了喵  ⁧~喵⁧‭] #鸣潮数据坞
[21:15:22.328][INFO][群号, 群员][#鸣潮数据坞][鸣潮-数据坞(calabash)][开始处理]
[21:15:22.565][INFO][TRSSYz] 获取可用性成功：账号可用
[21:15:22.622][INFO][TRSSYz] 获取我的资料成功
[21:15:22.679][INFO][TRSSYz] 获取数据坞成功
[21:15:22.680][ERRO][鸣潮-数据坞(calabash)][群号, 群员][#鸣潮数据坞] TypeError: Cannot read properties of null (reading 'phantomList')
    at Render.calaBashData (file:///home/ubuntu/Yunzai/plugins/waves-plugin/model/render.js:37:27)
    at Calabash.calabash (file:///home/ubuntu/Yunzai/plugins/waves-plugin/apps/Calabash.js:51:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///home/ubuntu/Yunzai/lib/plugins/loader.js:253:41) {
  [stack]: "TypeError: Cannot read properties of null (reading 'phantomList')\n" +
    '    at Render.calaBashData (file:///home/ubuntu/Yunzai/plugins/waves-plugin/model/render.js:37:27)\n' +
    '    at Calabash.calabash (file:///home/ubuntu/Yunzai/plugins/waves-plugin/apps/Calabash.js:51:48)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PluginsLoader.deal (file:///home/ubuntu/Yunzai/lib/plugins/loader.js:253:41)',
  [message]: "Cannot read properties of null (reading 'phantomList')"
}

**Comment by CikeyQi** [comment]
在库街区APP中的 `数据终端` 内打开所有项目的 `对外展示` 开关
